name: SkyWarsTeamDoDo
main: KaitoDoDo\SkyWarsTeam\SkyWarsTeam
author: KaitoDoDo
version: 2.0.0
api: 
- 1.0.0
- 1.1.0
- 2.0.0

commands:
    stm:
        usage: /stm <leave-make>
        description: SkyWars-Commands
    lang:
        usage: /lang <en>
        description: SkyWars-English-Lang
    rankstm:
        usage: /rankstm
        description: SkyRank-Commands
    stmstart:
        usage: /stmstart
        description: SkyWars-Force start
    resetmap:
        usage: /resetmap
        description: reset-the-map